In [1]:
# Function returning kmers of a particular DNA sequence
function gen_kmer(seq, k)
    kmers = []
    for i = 1:length(seq) - k + 1      # For the range lasting for number of kmers produced
        km = seq[i : i+k - 1]          # Creating substrings from current position to current position + k
        push!(kmers, km)               # Appending the kmers produced to the list
    end
    return kmers                       # Returning list of kmers
end

gen_kmer (generic function with 1 method)

In [2]:
# Performs sorting in lexicographic order
function bub_sort(s)
    seq = copy(s)                      
    for i = 1:length(seq) - 1          
        for j = 1:length(seq) - 1    
            if seq[j] > seq[j+1]       
                temp = seq[j]               
                seq[j] = seq[j + 1]    
                seq[j + 1] = temp 
            end
        end
    end
    return seq                         
end

bub_sort (generic function with 1 method)

In [3]:
# Returns all possible rotations of a given string
function rots(seq)
    n = length(seq)
    rotseq = []
    s = seq                            # Creates the duplicate of the given string 
    for i = 1:n
        s = string(s[2:n], s[1])       # Appends the last character with the rest of the string  
        push!(rotseq, s)               # Stores the new string in the empty array
    end
    return rotseq                      # Returns the final array for all the possible rotations
end 

rots (generic function with 1 method)

In [4]:
# Returns the Burrows-Wheeler tranform of a given string
function BWT(lex)
    st = ""                                     # Creating an empty string
    for i = 1:length(lex)
        st = string(st, lex[i][length(lex)])    # Appending the last character of the string to the empty array
    end
    return st
end

BWT (generic function with 1 method)

In [5]:
# Returns the index of a particular string for a given array
function str_match(sl, seq)                   
    ind = 0
    for i = 1:length(sl)
        if sl[i] == seq              # When the given string matches a 
            ind = i                  # particular index of the given BWT matrix
        end                         
    end
    return ind                       # Return the index
end

str_match (generic function with 1 method)

In [6]:
# Appends the last column (BWT) and order them lexicographically
function BWT_mat(pl, seq)
    n = length(pl)
    apnd_seq = copy(seq)
    for i = 1:n
        ss = pl[i]
        apnd_seq[i] = string(ss, apnd_seq[i]) 
    end
    return apnd_seq
end

BWT_mat (generic function with 1 method)

In [7]:
# Performs inverse Burrows-Wheeeler transform for a given BWT sequence
function inv_BWT(bwt, ind)
    null = fill("", length(bwt))
    fin = BWT_mat(bwt, null)
    for i = 1:length(bwt) - 1
        fin = BWT_mat(bwt, bub_sort(fin))
    end
    fin = bub_sort(fin)
    return fin[ind]
end

inv_BWT (generic function with 1 method)

In [8]:
# Using Suffix Arrays to implement Burrows-Wheeler Transform
function BWT_sufarr(seq)
    """
    Step 1
    ----------------------------------------------------------------------
         * Create an empty list and append all the posssible suffixes 
           by gradually increasing the size of the suffixes from 1 to
           length of the given input string and arranges the produced array
           in Lexicographic order.
    ----------------------------------------------------------------------
    """
    n = 1
    suffix = []
    for i = 1:length(seq)
        push!(suffix,seq[n:length(seq)])
        n += 1
    end
    suffix_nw = bub_sort(suffix)
    
    """
    Step 2
    ---------------------------------------------------------------------
        * Compare the new sorted suffixes with the unsorted suffixes
          and store the index of successive smallest suffixes occuring
          into a new array thereby creating a suffix array.
    ---------------------------------------------------------------------
    """
    sufx_arr = []
    for i = 1:length(suffix_nw)
        push!(sufx_arr, str_match(suffix, suffix_nw[i]))
    end
    
    """
    Step 3
    -------------------------------------------------------------------------
        * We then go to the character of the original string, pointed by 
          the index present in the suffix array and move one sport to the
          left and then store those in am empty string. At last we have the
          BWT sequence.
    -------------------------------------------------------------------------
    """
    bwt = ""
    for i = 1:length(sufx_arr)
        index = sufx_arr[i] - 1 
        if index == 0
            bwt = string(bwt, seq[length(seq)])
        else
            bwt = string(bwt, seq[index])
        end
    end
    return bwt
end

BWT_sufarr (generic function with 1 method)

In [9]:
seq = "BANANA1"
@time begin
    seq1 = BWT_sufarr(seq)
    print("The BWT result of $seq using Suffix Arrays is ", seq1)
    print("\nRun time of the BWT suffix algorithm is:")
end

The BWT result of BANANA1 using Suffix Arrays is ANNB1AA
Run time of the BWT suffix algorithm is:  0.209033 seconds (99.28 k allocations: 4.935 MiB)


In [10]:
function comp(str)
    c_str = ""
    i = 1
    while (i <= length(str))
        count = 1
        ch = str[i]
        j = i
        while (j < length(str))
            if (str[j] == str[j + 1])
                count = count + 1
                j = j + 1
            else
                break
            end
        end
        c_str = string(c_str, ch, count)
        i = j + 1
    end
    return c_str
end

comp (generic function with 1 method)

In [11]:
function decomp(c)
    dcomp = ""
    s = ""
    for i = 1:length(c)
        if tryparse(Float64, string(c[i])) != nothing
            n = parse(Int64, c[i])
        for j = 1:n
            s = string(s, c[i - 1])
        end
        end
    end
    dcomp = string(dcomp, s)
    return dcomp
end

decomp (generic function with 1 method)

In [12]:
seq = "BANANA1"
@time begin
    mat = rots(seq)
    print("Given input sequence is ", seq)
    #print("\nPossible rotations for the given sequence are ", mat)

    lx = bub_sort(mat)
    #print("\nSorted array of these possible rotations are ", lx)

    pr = BWT(lx)
    print("\nRun time of the BWT algorithm is:")
end
print("\nBurrows-Wheeler Transform for the given sequence is ", pr)

index = str_match(lx, seq)
fin_str = inv_BWT(pr, index)
print("\nInverse Burrows-Wheeler Transform for the given input is ", fin_str)
(seq == fin_str) && print("\nThe Genome sequences before performing BWT and after performing Inverse BWT are same")

Given input sequence is BANANA1
Run time of the BWT algorithm is:  0.086891 seconds (68.34 k allocations: 3.476 MiB)

Burrows-Wheeler Transform for the given sequence is ANNB1AA
Inverse Burrows-Wheeler Transform for the given input is BANANA1
The Genome sequences before performing BWT and after performing Inverse BWT are same

In [13]:
# Returns the Offset for the given BWT
function offset(seq1)
    ofst = []
    ar = collect(seq1)
    sorted = join(bub_sort(ar))
    for i = 1:length(seq1)
        push!(ofst, findfirst(ar[i], sorted)[1])
    end
    return bub_sort(unique(ofst))
end

offset (generic function with 1 method)

In [14]:
# Return the FM index matrix for the given BWT
function FM_ind(seq1)
    count = 0
    org = collect(seq1)
    unq = bub_sort(unique(org))
    fm_ind = zeros(Int8, length(org), length(unq))
    for i = 1:length(unq)
        for j = 1:length(org)
            if unq[i] == org[j]
                fm_ind[j,i] = count + 1
                count += 1
            else
                fm_ind[j,i] = count
            end
        end
        count = 0
    end
    return [zeros(Int8, 1, length(unq)); fm_ind]
end

FM_ind (generic function with 1 method)

In [15]:
function exct_mtch(p, seq1)
    F = FM_ind(seq1)
    O = offset(seq1)
    lo = 1 
    hi = size(FM_ind(seq1))[1]
    idx = join(bub_sort(unique(collect(seq1))))
    q = reverse(p)
    for i = 1:length(q)
        id = findfirst(q[i], idx)[1]
        lo = O[id] + F[lo,id]
        hi = O[id] + F[hi,id]
    end
    return [lo,hi]
end

exct_mtch (generic function with 1 method)

In [35]:
of = offset(seq1)
print("Offset for the sequence $seq1 is $of")

fm = FM_ind(seq1)
print("\nFM index matrix of the sequence $seq1 is\n")
show(stdout, "text/plain", fm)

p = "NA" 
match = exct_mtch(p, seq1)
print("\nThe starting and ending index of the given pattern $p in the original string $seq is $match")

Offset for the sequence ANNB1AA is Any[1, 2, 5, 6]
FM index matrix of the sequence ANNB1AA is
8×4 Array{Int8,2}:
 0  0  0  0
 0  1  0  0
 0  1  0  1
 0  1  0  2
 0  1  1  2
 1  1  1  2
 1  2  1  2
 1  3  1  2
The starting and ending index of the given pattern NA in the original string BANANA1 is [6, 8]

In [39]:
match = exct_mtch("BA", seq)

2-element Array{Int64,1}:
 6
 6

In [18]:
# Randomly generating a 100 length DNA sequence and extracting kmers from it
using Random
a = randstring("ATGC", 100)    # Random generation of a DNA sequence
k = 10                         # k-mer length
DNA = gen_kmer(a, k)           # Generating k-mers
a

"GGCATAGACTGGTGGTCCAGTCACATAACATCTTACCTATCGACCCCGGCCAGTTGATATCGTCTCAGTTGCTCCGAATAGCCTTTTAATCTGCCAGCGT"

In [19]:
print("Given input Genome sequence is $a\n")
print("\nLength of the given sequence is ", length(a), "\n")

print("\nThe list of kmers (k = $k) that we get from the given sequence are: ", DNA, "\n")

@time begin
    rot = [rots(DNA[i]) for i = 1:length(DNA)]
    sorted = [bub_sort(rot[i]) for i = 1:length(rot)]
    bw = [BWT(sorted[i]) for i = 1:length(sorted)]
    print("\nRun time of the BWT algorithm is:")
end

print("\nBurrows-Wheeler Transform for the set of given kmers are ", bw, "\n")

cp = [comp(bw[i]) for i = 1:length(bw)]
print("\nCompressed output of BWT sequences of all the kmers are ", cp, "\n")

dcp = [decomp(cp[i]) for i = 1:length(bw)]
print("\nDecompressed output of all the compressed BWT sequences are ", dcp, "\n")

@time begin
    match = [str_match(sorted[i], DNA[i]) for i = 1:length(bw)]
    inv = [inv_BWT(bw[i], match[i]) for i = 1:length(bw)]
end
print("\nInverse Burrows-Wheeler Transform for the given input of BWT sequences are ", inv, "\n")

(inv == DNA) && print("\nThe Kmers before performing BWT and after performing Inverse BWT are same")

Given input Genome sequence is GGCATAGACTGGTGGTCCAGTCACATAACATCTTACCTATCGACCCCGGCCAGTTGATATCGTCTCAGTTGCTCCGAATAGCCTTTTAATCTGCCAGCGT

Length of the given sequence is 100

The list of kmers (k = 10) that we get from the given sequence are: Any["GGCATAGACT", "GCATAGACTG", "CATAGACTGG", "ATAGACTGGT", "TAGACTGGTG", "AGACTGGTGG", "GACTGGTGGT", "ACTGGTGGTC", "CTGGTGGTCC", "TGGTGGTCCA", "GGTGGTCCAG", "GTGGTCCAGT", "TGGTCCAGTC", "GGTCCAGTCA", "GTCCAGTCAC", "TCCAGTCACA", "CCAGTCACAT", "CAGTCACATA", "AGTCACATAA", "GTCACATAAC", "TCACATAACA", "CACATAACAT", "ACATAACATC", "CATAACATCT", "ATAACATCTT", "TAACATCTTA", "AACATCTTAC", "ACATCTTACC", "CATCTTACCT", "ATCTTACCTA", "TCTTACCTAT", "CTTACCTATC", "TTACCTATCG", "TACCTATCGA", "ACCTATCGAC", "CCTATCGACC", "CTATCGACCC", "TATCGACCCC", "ATCGACCCCG", "TCGACCCCGG", "CGACCCCGGC", "GACCCCGGCC", "ACCCCGGCCA", "CCCCGGCCAG", "CCCGGCCAGT", "CCGGCCAGTT", "CGGCCAGTTG", "GGCCAGTTGA", "GCCAGTTGAT", "CCAGTTGATA", "CAGTTGATAT", "AGTTGATATC", "GTTGATATCG", "TTGATATCGT", "T

In [20]:
@time begin
    bw1 = [BWT_sufarr(DNA[i]) for i = 1:length(DNA)]
    print("\nRun time of the BWT algorithm using suffix array approach is:")
end
print("\nBurrows-Wheeler Transform for the set of given kmers using suffix array approach are ", bw1)


Run time of the BWT algorithm using suffix array approach is:  0.028613 seconds (69.76 k allocations: 3.602 MiB)

Burrows-Wheeler Transform for the set of given kmers using suffix array approach are ["GTCGAAGTCA", "GTCGATAGAC", "GTCGAGATAC", "GTTAATGGAC", "GTATATGGGC", "GGAGATTGGC", "GATTTGGGGC", "CTATTGGGGC", "CTCTTGGGGC", "CCTTTGGGGA", "CCTATGGGGG", "CCTTAGTGGG", "CTCTTAGGGC", "CCTCTAAGGG", "CCATCTACGG", "CCCATCTAGA", "CCCTCATAAG", "TCCCTAAAAG", "ATCACTAAAG", "TACCATACAG", "CTACCATAAA", "TACCCTAAAA", "TCACCTAAAA", "TACCTATCAA", "TATCATTAAC", "TTACATTAAC", "CTACAATTAC", "CTCCAATTAC", "TCTACTCTAC", "TTAACTCTAC", "TTACTATCTC", "TTTACCTCAC", "TTATCCTCAG", "GTTATCCACA", "GCTAATCCCA", "GTCACTCCCA", "GTCCATCCCA", "GTCCCATCCA", "GGACCCTCCA", "GACCTCGCCG", "GGACCCCCGC", "GCGACCCCGC", "CACGACCCGC", "CCGGCCCAGC", "CCGTCCGCAG", "CCGTCGCATG", "CCGGTGCATG", "GCCGTGAATG", "CGCGTTAATG", "TCGCATAATG", "CTGTTAAATG", "CGTTTAAATG", "GTTCTGAATG", "GTTTCGAATT", "GTTTTCAGAC", "GTTTTCCAAG", "CTTTTCACAG", "

In [22]:
display("text/plain", rand(40, 5))

40×5 Array{Float64,2}:
 0.0136439  0.121494   0.429656   0.00109431  0.410791
 0.749706   0.916926   0.404826   0.570115    0.559206
 0.391298   0.903084   0.726446   0.241023    0.513588
 0.727176   0.32751    0.211949   0.795251    0.201668
 0.470397   0.0779795  0.0539352  0.573416    0.315319
 0.839373   0.819732   0.33745    0.928856    0.810221
 0.135059   0.0274831  0.786552   0.756916    0.373203
 0.719695   0.261514   0.978445   0.293468    0.0818716
 0.210191   0.496803   0.578893   0.264677    0.181221
 0.886348   0.473514   0.418513   0.386716    0.873227
 0.175871   0.401301   0.454777   0.189774    0.502237
 0.824807   0.0636796  0.670597   0.552806    0.809105
 0.023616   0.565006   0.758697   0.530499    0.375115
 ⋮                                            
 0.133603   0.816828   0.874101   0.0375901   0.0915989
 0.176753   0.74944    0.36829    0.119969    0.102924
 0.902753   0.805697   0.126425   0.904894    0.274449
 0.658706   0.117031   0.329764   0.171313    0.